"""Deterministic quantitative primitives for the M16A engineering layer."""

from .quantities import (
    UNIT_REGISTRY_VERSION,
    ConversionRecord,
    DecimalParseError,
    QuantityKind,
    QuantityKindMismatchError,
    QuantifiedValue,
    QuantityValidationError,
    UnitDefinition,
    UnknownUnitError,
    canonical_decimal_text,
    convert_quantity,
    parse_decimal,
)
from .serialization import (
    CANONICAL_JSON_VERSION,
    CanonicalSerializationError,
    canonical_json_bytes,
    canonical_sha256,
)
from .problem import (
    CANDIDATE_CONTENT_IDENTITY_VERSION,
    COMPILER_POLICY_VERSION,
    EPR_CONTENT_IDENTITY_VERSION,
    HEAT_SOURCE_CONSISTENCY_POLICY_VERSION,
    PROBLEM_FORMAT_VERSION,
    EngineeringProblem,
    EngineeringProblemValidationError,
    candidate_content_sha256,
    engineering_problem_content_sha256,
)
from .compiler import (
    CompilationFailure,
    CompiledEngineeringProblem,
    compile_engineering_problem,
    write_engineering_problem,
)

__all__ = [
    "CANONICAL_JSON_VERSION",
    "CANDIDATE_CONTENT_IDENTITY_VERSION",
    "COMPILER_POLICY_VERSION",
    "EPR_CONTENT_IDENTITY_VERSION",
    "HEAT_SOURCE_CONSISTENCY_POLICY_VERSION",
    "PROBLEM_FORMAT_VERSION",
    "UNIT_REGISTRY_VERSION",
    "CanonicalSerializationError",
    "CompilationFailure",
    "CompiledEngineeringProblem",
    "ConversionRecord",
    "DecimalParseError",
    "EngineeringProblem",
    "EngineeringProblemValidationError",
    "QuantityKind",
    "QuantityKindMismatchError",
    "QuantifiedValue",
    "QuantityValidationError",
    "UnitDefinition",
    "UnknownUnitError",
    "canonical_decimal_text",
    "canonical_json_bytes",
    "canonical_sha256",
    "candidate_content_sha256",
    "compile_engineering_problem",
    "convert_quantity",
    "engineering_problem_content_sha256",
    "parse_decimal",
    "write_engineering_problem",
]
